### ISSUE TITLE
Problemas de permissão para escrita no Firebase

### ISSUE THREAD

**Issue by NaraSouza** [NaraSouza/if1001-AppChamada#11]
Como estamos em fase testes, nas regras do banco deixei leitura e escrita como "true", o que permite acesso aos dados sem estar autenticado. Porém, ao cadastrar um novo usuário (e o cadastro está sendo realizado com sucesso), não é possível adicionar as informações sobre o usuário no banco, por causa de erros de "permission denied". Pesquisando sobre o erro, vi que nos casos em que a permissão não é concedida mesmo estando como true, o problema é geralmente associado ao google-services.json. Substituí o arquivo no projeto por um recém baixado do console e não teve diferença. Exclui o aplicativo do projeto e adicionei de novo e nada. Criei outro aplicativo e o problema persiste. Ao modificar as permissões para pedir autenticação, o resultado é o mesmo, ainda que tenha um usuário autenticado.

**Comment by NaraSouza** [comment]
@leopoldomt o senhor tem ideia de como resolver isso?

**Comment by leopoldomt** [comment]
Como está o conteúdo do google-services.json? Está casando com o app id?

**Comment by NaraSouza** [comment]
Sim, o package name está correto no google-services.json.

**Comment by NaraSouza** [comment]
Criei um outro projeto no Firebase e importei a estrutura do anterior, mas não as regras. Leitura e escrita estão funcionando (além do login e cadastro), o que indica que o problema estava nas regras do projeto anterior, porém ainda não consegui identificar o que está causando o problema pois as leituras e escritas pelo simulador funcionam perfeitamente.
